variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - testing
  - building
  - deploying

# templates
.install-deps-template: &install-deps
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install poetry
    - poetry install -vv

.test-template: &test
  <<: *install-deps
  stage: testing
  coverage: '/TOTAL.*\s+(\d+\%)/'
  script: pytest --cov --cov-report html --cov-report term
  artifacts:
    paths:
      - tests/coverage
    when: always
    expire_in: 1 month

test:
  <<: *test
  image: python:$PYTHON_VERSION
  only:
    - master
  parallel:
    matrix:
      - PYTHON_VERSION: [ "3.9", "3.10", "3.11", "3.12" ]

pages:
  <<: *install-deps
  image: python:3.9
  stage: building
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd docs ; make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master

build:
  <<: *install-deps
  image: python:3.9
  stage: building
  script: poetry build
  artifacts:
    paths:
      - dist/*.whl
  only:
    - master

deploy:
  stage: deploying
  script: echo "would upload to PyPi"
  only:
    - tags