
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - testing
  - building
  - deploying

# templates
.install-deps-template: &install-deps
  before_script:
    - pip install poetry
    - poetry --version
    - source `poetry env info --path`/bin/activate
    - poetry install -vv


.test-template: &test
  <<: *install-deps
  stage: testing
  coverage: '/TOTAL.*\s(\d+\.\d+\%)/'
  script: pytest --cov
  artifacts:
    paths:
      - tests/logs
    when: always
    expire_in: 1 week


test_python3.8:
  <<: *test
  image: python:3.8

test_python3.9:
  <<: *test
  image: python:3.9

#test_python3.10:
#  <<: *test
#  image: python:3.10


pages:
  image: python:3.8
  stage: building
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd docs ; make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master

build:
  image: python:3.8
  stage: building
  script: poetry build
  artifacts:
    paths:
      - dist/*.whl

deploy:
  stage: deploying
  script: echo "would upload to PyPi"
