variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - testing
  - building
  - deploying

# templates
.install-deps-template: &install-deps
  before_script:
    - pip install uv
    - uv venv
    - source .venv/bin/activate
    - uv pip install -e .[dev]

.test-template: &test
  <<: *install-deps
  stage: testing
  coverage: '/TOTAL.*\s+(\d+\%)/'
  script: pytest --cov --cov-report html --cov-report term
  artifacts:
    paths:
      - tests/coverage
    when: always
    expire_in: 1 month

test:
  <<: *test
  image: python:$PYTHON_VERSION
  only:
    - master
  parallel:
    matrix:
      - PYTHON_VERSION: [ "3.9", "3.10", "3.11", "3.12" ]

pages:
  <<: *install-deps
  image: python:3.9
  stage: building
  script:
    - uv pip install sphinx sphinx-rtd-theme
    - cd docs ; make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master

build:
  <<: *install-deps
  image: python:3.9
  stage: building
  script:
    - uv pip install pdm-backend
    - python -m build
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz
  only:
    - master

deploy:
  stage: deploying
  image: python:3.9
  needs:
    - build
  before_script:
    - pip install uv
    - uv venv
    - source .venv/bin/activate
    - uv pip install twine
  script:
    - twine upload --repository pypi dist/*
  only:
    - tags
  environment:
    name: pypi
    url: https://pypi.org/project/pyechelle/