image: python:3.8

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install poetry
  - poetry install -E optional_dep

test:
  script:
    - pytest --cov

    #run:
    #  script:
    #    - python setup.py bdist_wheel
    # an alternative approach is to install and run:
    #    - pip install dist/*
    # run the command here
#  artifacts:
#    paths:
#      - dist/*.whl

pages:
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd docs ; make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master
